version: "3.7"

services:
  postgres:
    image: postgres:15.1
    container_name: postgresql
    ports:
    - "5432:5432"
    volumes:
      - /data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: belko
      POSTGRES_DB: auction
      POSTGRES_USER: belko

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: nodejs-rabbitmq-rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=belko
      - RABBITMQ_DEFAULT_PASS=belko